### ISSUE TITLE
Revisión del trabajo

### ISSUE THREAD

**Issue by SirJoc** [SirJoc/TF_Algoritmos#7]
 Debe construir haciendo uso de Programación Orientada a Objetos (POO).

 Debe diseñar los tipos de datos abstractos.

 Debe construir de la manera más desacoplada posible. Las de estructuras de
datos usadas deben hacer uso de plantillas (templates), de tal forma que
construir su código no involucre modificar código de estructuras, mas sólo
instanciar objetos de estas para utilizarlos.

 La interfaz de usuario puede utilizar Windows Forms o CLI.

 Gestión del proyecto con github (milestones, issues).

**Comment by brunotiglla** [comment]
terminado
