### ISSUE TITLE
Informe

### ISSUE THREAD

**Issue by SirJoc** [SirJoc/TF_Algoritmos#8]
1. Introducción
2. Índice
3. Objetivo del Estudiante (Student Outcome)
4. Capítulo 1: Presentación
5. Capítulo 2: Marco conceptual
6. Capítulo 3: Diseño del proyecto
a. Diseño de un plan de proyecto de desarrollo de soluciones en ingeniería
con las restricciones establecidas considerando asignación de recursos,
milestones, issues.
7. Capítulo 4: Diseño del producto
a. Definición de las necesidades específicas considerando el impacto en salud
pública, seguridad, bienestar y factores globales, culturales, sociales,
ambientales y económicos.
b. Definición de requisitos funcionales y no funcionales
c. Elaboración de diagrama de clases
d. Diseño de la interfaz de usuario
e. Diseño de tipos de datos abstractos
f. Selección de estructuras de datos
8. Capítulo 5: Diseño del proceso de desarrollo de la solución
a. Diseño de la arquitectura del software
b. Implementación de las funcionalidades del software.
c. Pruebas del software
9. Conclusiones 
10. Bibliografía
11. Anexos (ppt, video, otros)

**Comment by brunotiglla** [comment]
Termiando
